[build]
  functions = "functions"
  command = """
    npm run create-env && \
    envsubst < public/window-env.js.template > dist/window-env.js && \
    npm run build:prod
  """
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "23.3.0" }

[[plugins]]
  package = "netlify-plugin-inline-source"
    [plugins.inputs]
      attribute = "inline"